[package]
name = "shoreview"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
stl_io = "0.7"
clap = { version = "4.5", features = ["derive"] }
bevy_brp_extras = "0.2"
